# Simple calculator

In [1]:

    a = int(input('Enter the value of a : '))
    b = int(input('Enter the value of b : '))
    op = str(input('Enter the operator'))
    if(op == '+'):
        print(a+b)
    elif(op == '-'):
        print(a-b)
    elif(op == '*'):
        print(a*b)
    elif(op == '/'):
        print(a/b)
    elif(op == '**'):
        print(a**b)
    elif(op == '//'):
        print(a//b)
    else:
        print('invalid operator')
        
    

Enter the value of a : 5
Enter the value of b : 6
Enter the operator+
11


# Python program to print a table

In [2]:
n = int(input('enter the table'))
i = 1
while(i<=10):
    print(n ,'x' , i , '=' , n*i)
    i = i+1

enter the table99
99 x 1 = 99
99 x 2 = 198
99 x 3 = 297
99 x 4 = 396
99 x 5 = 495
99 x 6 = 594
99 x 7 = 693
99 x 8 = 792
99 x 9 = 891
99 x 10 = 990


# Python program for sum of squares of the first 15 natural numbers using a while loop. 

In [3]:
sum = 0
i = 1
while(i<=15):
    sum = sum+i**2
    i = i+1
print(sum)

1240


# Prime Numbers and Python While Loop
Using a while loop, we will construct a Python program to verify if the given integer is a prime number or not.

In [4]:
num = int(input('enter the number: '))
if num > 1:
    # Iterate from 2 to n / 2
    for i in range(2, int(num/2)+1):
        # If num is divisible by any number between
        # 2 and n / 2, it is not prime
        if (num % i) == 0:
            print(num, "is not a prime number")
            break
    else:
        print(num, "is a prime number")
else:
    print(num, "is not a prime number")

enter the number: 3
3 is a prime number


# Factorial of a number

In [5]:
n = int(input('enter the value'))
fact = 1
for i in range(1,n+1):
    fact = fact*i
print(fact)

enter the value5
120


# Fibonacci series

In [6]:
n = int(input('Enter the value'))
n1 = 0
n2 = 1
print(n1)
print(n2)
for i in range(2,n+1):
    n3 = n1+n2
    n1 = n2
    n2 = n3
    print(n3)

Enter the value10
0
1
1
2
3
5
8
13
21
34
55


In [7]:
for string in "While Loops":  
    if string == "o" or string == "i" or string == "e":  
         continue  
    print('Current Letter:', string)  

Current Letter: W
Current Letter: h
Current Letter: l
Current Letter:  
Current Letter: L
Current Letter: p
Current Letter: s


In [8]:
for string in "Python Loops":  
    if string == 'n':  
         break  
    print('Current Letter: ', string)  

Current Letter:  P
Current Letter:  y
Current Letter:  t
Current Letter:  h
Current Letter:  o


In [10]:
for string in "Python Loops":  
    pass  
print( 'Last Letter:', string)   

Last Letter: s


# Swapping numbers

Using a temporary variable

In [1]:
# Python program to swap two variables

x = 5
y = 10
temp = x
x = y
y = temp
print(x)
print(y)

10
5


Without Using Temporary Variable

In [2]:
x = 5
y = 10

x, y = y, x
print("x =", x)
print("y =", y)

x = 10
y = 5


Addition and Subtraction

In [3]:
x = 5
y = 10
x = x + y
y = x - y
x = x - y
print(x)
print(y)

10
5


Multiplication and Division

In [4]:
x = 5
y = 10
x = x * y
y = x / y
x = x / y
print(x)
print(y)

10.0
5.0


XOR swap

This algorithm works for integers only

In [5]:
x = 5
y = 10
x = x ^ y
y = x ^ y
x = x ^ y
print(x)
print(y)

10
5


# write a python program to print greeting according to the time 

In [16]:
import time
timestamp = time.strftime('%H:%M:%S')
hours = int(time.strftime('%H'))
minutes = int(time.strftime('%M'))
seconds = int(time.strftime('%S'))
print(timestamp)
if(hours<=11 and minutes <=59):
    print("good morning")
elif(hours>=12 or hours<3):
    print("good afternoon")
elif(hours>=3 or hours <6):
    print("good evening")
else:
    print("good night")


12:21:30
good afternoon


In [1]:
7>>2

1

In [2]:
7<<2

28

In [3]:
bin(7)

'0b111'

In [4]:
bin(2)

'0b10'

In [5]:
125|265

381

In [6]:
i = 0
while(i<10):
    print("hello world")
    i+=1

hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world


#  Numbers that are not divisible by 3 and 5 between 1-100

In [9]:
for i in range(1,101):
    if(i%3==0 or i%5== 0):
        continue
    print(i)

1
2
4
7
8
11
13
14
16
17
19
22
23
26
28
29
31
32
34
37
38
41
43
44
46
47
49
52
53
56
58
59
61
62
64
67
68
71
73
74
76
77
79
82
83
86
88
89
91
92
94
97
98


# printing square pattern

In [14]:
for i in range(5):
    for j in range(5):
        print('#',end=" ")
    print()
    

# # # # # 
# # # # # 
# # # # # 
# # # # # 
# # # # # 


# printing triangle

In [15]:
for i in range(5):
    for j in range(i):
        print("#",end = " ")
    print()


# 
# # 
# # # 
# # # # 


In [17]:
for i in range(5):
    for j in range(i):
        print("#",end = " ")
    print()


# 
# # 
# # # 
# # # # 


In [19]:
for i in range(5):
    for j in range(5-i):
        print(i,end = " ")
        
    print()

0 0 0 0 0 
1 1 1 1 
2 2 2 
3 3 
4 


# Prime numbers

In [28]:
x = int(input("enter the number"))
if(x>1):
    
    
    for i in range(2,int(x/2)+1):
        if(x%i==0):
            print("not prime")
            break
    else:
        print("prime")
else:
    print("not prime")

enter the number3
prime


In [29]:
num = int(input('enter the number: '))
if num > 1:
    # Iterate from 2 to n / 2
    for i in range(2, int(num/2)+1):
        # If num is divisible by any number between
        # 2 and n / 2, it is not prime
        if (num % i) == 0:
            print(num, "is not a prime number")
            break
    else:
        print(num, "is a prime number")
else:
    print(num, "is not a prime number")

enter the number: 5
5 is a prime number


# Factorial 

In [31]:
x = int(input("enter the number"))
res = 1
for i in range(1,x+1):
    res = res*i
print(res)

enter the number5
120


In [32]:
import numpy as np

In [33]:
a = np.array([1,2,3,4,5])

In [34]:
a

array([1, 2, 3, 4, 5])

In [35]:
type(a)

numpy.ndarray

In [36]:
b = np.arange(0,20,2)

In [37]:
b

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [41]:
c = np.linspace(1,10,10)

In [42]:
c

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [43]:
d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [44]:
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
d = np.zeros([3,3])

In [49]:
d

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [50]:
d = np.ones([3,3])

In [51]:
d

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [55]:
d = np.eye(4)

In [56]:
d

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [1]:
a = 4
bin(a)

'0b100'

In [2]:
oct(a)

'0o4'

In [3]:
hex(a)

'0x4'

In [4]:
a = 3
b = 4
a,b = b,a

In [5]:
a


4

In [6]:
b

3

In [7]:
a = a+b
b = a-b
a = a - b

In [8]:
a

3

In [9]:
b

4

# Kvargs

In [14]:
def person(name,**data):
    print(name)
    print(data)
    for i,j in data.items():
        print(i,j)
    
p = person("vignesh" , age = 21, place="hyd")

vignesh
{'age': 21, 'place': 'hyd'}
age 21
place hyd


In [17]:
lst = [1,2,3,4,5,6,7,8,9,10]
def count(lst):
    even = 0
    odd = 0
    for i in lst:
        if(i%2==0):
            even+=1
        else:
            odd+=1
    print("even : " , even)
    print("odd : " , odd)
count(lst)

even :  5
odd :  5


In [13]:
def fib(n):
    a = 0
    b = 1
    if n == 1:
        print(a)
    elif(n<1):
        print("invalid number")
    else:
        print(a)
        print(b)
        for i in range(2,n+1):
            c = a+b
            a = b
            b = c
            print(c)
fib(10)

0
1
1
2
3
5
8
13
21
34
55


In [16]:
def fact(n):
    res = 1
    for i in range(1,n+1):
        res = res*i
    return res

fact(5)
        

120